### PR TITLE
bump all examples/ gradle wrapper version to 6.3

### PR DESCRIPTION
**Pull request by paulvi**
ref #46

1 gradle download should be enough

### CODE REVIEW

**Comment by nschwermann** [comment]
My current PR updates wrapper to 6.8 https://github.com/emeraldpay/polkaj/pull/61

**Comment by paulvi** [comment]
OK, which ever get's merged first,

there should not be 3 gradle versions in one project

**Comment by nschwermann** [comment]
Hmm, okay. In the meantime you don't need to use the wrapper at all you can use `gradle` instead of `./gradlew`

**Comment by paulvi** [comment]
Thanks, I know

Well, with the pace of gradle changes, global gradle can do only maybe for the same major version

And IDEA bundles its own gradle version, in the end that leads to unclear situation, like what exact gradle instance is running

image

**Comment by paulvi** [comment]
resolved with #61

**Pull request closed without merging**
