### PR TITLE
Metadata v12/refCount size change + misc fixes, improvements

### PR DESCRIPTION
**Pull request by pablojorge**
# Intro

This PR adds support for newer versions of Polkadot and introduces several improvements and fixes.

# Changes

## Support for Metadata v12 and refcount size change

In Polkadot v0.8.25 (https://github.com/paritytech/polkadot/releases/tag/v0.8.25), the metadata was updated to v12 (to include a new `index` field for modules) and the `refcount` field of `AccountInfo` was extended from 8 to 32 bits.

Commits:
 * https://github.com/blockchain/polkaj/commit/0ef40aa7b519a58b5baf2130bafddc68430d4e81
 * https://github.com/blockchain/polkaj/commit/1ca8dec411e25ed9fcecdd79e98a314704a0c7da
 
References:
 * https://github.com/paritytech/substrate/pull/6969
 * https://github.com/paritytech/substrate/pull/7164

Related issues:
 * https://github.com/emeraldpay/polkaj/issues/29
 * https://github.com/emeraldpay/polkaj/issues/30
 * https://github.com/emeraldpay/polkaj/issues/39
 
### CompactBigIntWriter fix

The following commit fixes the serialization of CompactBigInts when the MSB is > 127, and the resulting byte array starts with an extra 0x00 (to signal it's a positive value):
 * https://github.com/blockchain/polkaj/commit/74500e94e189be5f2ff40aedd10f1762b5343f04

Related issues:
 * https://github.com/emeraldpay/polkaj/issues/32
 
### Mortal era encoding fix

The following commit fixes the serialization of Mortal eras on both the signature payload and the transaction info of the extrinsic:
 * https://github.com/blockchain/polkaj/commit/ed3d0b58c68168a76892f01d12e236eb9e8067a6
 
Additionally, it extends the `ExtrinsicContext.Builder` class to allow setting the `era` and `eraBlockHash` fields.

## Improvements

The PR also extends the `PolkadotHttpApi` constructor and builder to accept a `timeout` parameter, and extends the `RpcException` class to include the `data` field from JSON error responses.

Commits:
 * https://github.com/blockchain/polkaj/commit/3b7eadc20363342373f84ed4e7d30bf99ab7cb90
 * https://github.com/blockchain/polkaj/commit/4db9ecb55f241a2226d193cd3cac09794d77ae82

### CODE REVIEW

**Comment by splix** [comment]
@pablojorge thank you very much for the PR, it fixes few very critical issues. I've checked the commit, everything is good. 

The only thing I would comment on is having the _Era_ codec as method in Scale Reader/Writer. I prefer to use the main scale class to provide methods only for basic and common types, and use a generic method (`write(ScaleWriter<T> writer, T value)`) for other types. I mean that's fine right now, not critical at all, and I'm going to merge your changes as is. Just saying that if you are planing to implement other codecs.

**Comment by pablojorge** [comment]
Sure! We're glad to contribute!

Regarding the Era codec, yes, maybe adding the methods wasn't really necessary, will have in mind that if we add more

**Comment by EmilyCaoHong** [comment]
can you give all of the projects jar or the download url

**Comment by nschwermann** [comment]
Hey guys, where is the metadata found? I can get support for new metadata version (13)

**Pull request merged**
